[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.api"
watchPatterns = [
  "/**/*.py",
  "/requirements.lock.txt",
  "/Dockerfile.api",
  "/alembic.ini",
  "/migrations/**",
]

[deploy]
preDeployCommand = ["python -m alembic upgrade head"]
healthcheckPath = "/live"
healthcheckTimeout = 300
restartPolicyType = "ALWAYS"
overlapSeconds = 30
drainingSeconds = 30
