import { LegalPageShell, type LegalSection } from "@/components/legal-page-shell"
import { PublicContactDetails } from "@/components/public-contact-details"

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance" },
  { id: "eligibility", title: "Eligibility" },
  { id: "accounts", title: "Accounts" },
  { id: "service", title: "Service" },
  { id: "content", title: "Your Content" },
  { id: "ai-output", title: "AI Output" },
  { id: "technical-rounds", title: "Technical Rounds" },
  { id: "acceptable-use", title: "Acceptable Use" },
  { id: "payments", title: "Payments" },
  { id: "refunds", title: "Refunds" },
  { id: "third-parties", title: "Third Parties" },
  { id: "privacy", title: "Privacy" },
  { id: "availability", title: "Availability" },
  { id: "ip", title: "IP Rights" },
  { id: "disclaimers", title: "Disclaimers" },
  { id: "liability", title: "Liability" },
  { id: "law", title: "India Law" },
  { id: "contact", title: "Contact" },
]

export default function TermsPage() {
  return (
    <LegalPageShell
      eyebrow="Legal"
      title="Terms of Service and Terms of Use"
      description="These Terms govern access to and use of InterAI's interview simulation, resume-based coaching, technical rounds, code execution, billing, and related services."
      updated="June 2, 2026"
      sections={sections}
    >
      <section id="acceptance">
        <h2>1. Acceptance of these Terms</h2>
        <p>
          These Terms of Service and Terms of Use form a binding agreement between you and InterAI
          ("InterAI", "we", "us", or "our"). By creating an account, signing in with Google,
          uploading a resume, starting an interview, running code, purchasing a plan or credits, or
          otherwise using the website, application, APIs, dashboards, interview rooms, technical
          workspaces, reports, or support channels, you agree to these Terms.
        </p>
        <p>
          If you use InterAI for an organization, school, team, or other entity, you represent that
          you have authority to bind that entity. If you do not agree to these Terms, do not use the
          service.
        </p>
      </section>

      <section id="eligibility">
        <h2>2. Eligibility and user responsibility</h2>
        <p>
          You must be legally able to enter into a contract under applicable law. Users under 18 may
          use InterAI only with permission and supervision from a parent or legal guardian. You are
          responsible for ensuring that your use of InterAI complies with laws, school rules,
          employer policies, interview rules, coding-assessment rules, and any confidentiality
          obligations that apply to you.
        </p>
        <p>
          InterAI is built for interview preparation and educational practice. It is not a hiring
          platform, employer, recruiter, background-check provider, immigration adviser, legal
          adviser, financial adviser, or professional certification authority.
        </p>
      </section>

      <section id="accounts">
        <h2>3. Accounts, authentication, and security</h2>
        <p>
          You may create an account using email and password or Google Sign-In when enabled. You
          must provide accurate account information, keep your credentials secure, and promptly tell
          us if you believe your account has been compromised. You are responsible for activity that
          occurs through your account unless caused by our breach of these Terms or our security
          obligations.
        </p>
        <p>
          We may require email verification, password complexity, login rate limits, CSRF protection,
          session cookies, or other security controls. We may refuse, suspend, limit, or terminate an
          account if we reasonably believe it is fraudulent, unsafe, abusive, legally risky, or used
          to bypass plan limits, anti-cheat controls, authentication, payments, or rate limits.
        </p>
      </section>

      <section id="service">
        <h2>4. What InterAI provides</h2>
        <p>
          InterAI provides AI-driven interview preparation tools, including resume parsing, job and
          role profile setup, mock interview sessions, speech transcription, interview scoring,
          coaching feedback, technical rounds, coding workspaces, code execution, learning exercises,
          dashboards, analytics, reports, support, and billing features.
        </p>
        <p>
          Features may vary by plan, geography, browser, device, availability of third-party
          providers, and product maturity. Some features are experimental or generated by AI, and may
          change, fail, produce inaccurate results, or be unavailable from time to time.
        </p>
      </section>

      <section id="content">
        <h2>5. Your resumes, answers, code, and other content</h2>
        <p>
          "User Content" means content you submit, upload, record, type, paste, import, create, or
          transmit through InterAI, including resumes, profile details, job targets, interview
          answers, transcripts, code, whiteboard data, technical submissions, support messages,
          feedback, and related files or metadata.
        </p>
        <p>
          You retain ownership of your User Content as between you and InterAI. You grant InterAI a
          worldwide, non-exclusive, royalty-free license to host, store, process, transmit, display,
          analyze, transform, summarize, score, and otherwise use User Content as needed to provide,
          secure, troubleshoot, maintain, support, and improve the service — including by sending
          content to third-party AI, speech, execution, and infrastructure providers as described in
          the Privacy Policy. This includes generating questions, feedback, reports, exercises, and
          technical-round evaluations.
        </p>
        <p>
          You represent that you have the rights and permissions needed to provide your User Content
          and that it does not violate law, confidentiality duties, employer rules, assessment
          rules, intellectual-property rights, privacy rights, or the rights of any third party. Do
          not upload proprietary employer material, confidential interview questions, private
          third-party data, government secrets, regulated data, or content you are not allowed to
          share.
        </p>
      </section>

      <section id="ai-output">
        <h2>6. AI-generated output, scores, and no hiring guarantee</h2>
        <p>
          InterAI may generate questions, follow-ups, hints, scoring rubrics, reports, coaching
          exercises, technical prompts, mistake analysis, and other output using automated systems
          and AI models. AI output can be incomplete, inaccurate, stale, biased, inconsistent, or
          unsuitable for your circumstances.
        </p>
        <p>
          Scores, feedback, readiness ratings, recommendations, and reports are practice guidance
          only. They do not guarantee job offers, interview outcomes, salary outcomes, admissions,
          promotions, certifications, legal compliance, or performance in a real interview. You are
          responsible for reviewing output, applying judgment, and deciding how to use feedback.
        </p>
      </section>

      <section id="technical-rounds">
        <h2>7. Technical rounds, monitoring, and code execution</h2>
        <p>
          Technical rounds may include timed prompts, Monaco editor workspaces, code snapshots,
          stdout and stderr capture, hidden or visible tests, run history, compiler or runtime
          errors, technical reports, and generated technical feedback. Code may be sent to a
          configured private isolated sandbox to compile, run, validate, and return results.
        </p>
        <p>
          Strict technical or mock sessions may request fullscreen, screen sharing, microphone,
          camera, speech recognition, or related browser permissions. InterAI may record or log
          anti-cheat and integrity events, including paste attempts, large code changes, tab
          switches, fullscreen exits, screen-share stops, suspicious fast submissions, blocked drops,
          visible-output hardcoding signals, and permission failures. Browser-based body-language
          analysis may process metrics in the browser and send only derived metrics where the
          product flow requires it.
        </p>
        <p>
          You may not submit code intended to attack, overload, bypass, scan, exfiltrate, mine
          cryptocurrency, persist, exploit, or interfere with InterAI, execution sandboxes,
          third-party services, networks, or other users. You may not use technical rounds to test
          malware, credential theft, spam tooling, evasion tooling, or unlawful automation.
        </p>
      </section>

      <section id="acceptable-use">
        <h2>8. Acceptable use</h2>
        <p>You agree not to use InterAI to:</p>
        <ul>
          <li>break the law, violate contracts, or infringe intellectual-property, privacy, or publicity rights;</li>
          <li>share another person's personal data without proper authority;</li>
          <li>harass, threaten, defame, exploit, discriminate against, or harm others;</li>
          <li>upload malicious files, malware, prompts, code, or payloads;</li>
          <li>reverse engineer, scrape, overload, crawl, benchmark abusively, or disrupt InterAI;</li>
          <li>bypass authentication, payment, rate limits, plan limits, anti-cheat, or security controls;</li>
          <li>misrepresent InterAI output as a human recruiter, employer decision, official certification, or guaranteed result;</li>
          <li>sell, lease, sublicense, or provide access to your account without our permission;</li>
          <li>use InterAI during a real interview, exam, or assessment where outside help is prohibited.</li>
        </ul>
      </section>

      <section id="payments">
        <h2>9. Plans, credits, payments, and billing</h2>
        <p>
          InterAI may offer free trials, interview credits, daily limits, paid memberships, monthly
          plans, annual plans, or other packages. Features, limits, prices, taxes, currencies, and
          included sessions may be shown at checkout or in membership screens and may change for
          future billing periods or future purchases.
        </p>
        <p>
          Payments are processed through Razorpay or another payment provider we identify at
          checkout. Your card, UPI, bank, wallet, EMI, or other payment credentials are handled by
          the payment provider according to its own terms and privacy policy. InterAI does not store
          full card numbers, CVV values, bank credentials, or raw UPI credentials.
        </p>
        <p>
          You authorize us and our payment providers to charge the selected payment method for the
          plan, credits, taxes, fees, and renewals you choose. You are responsible for payment
          failures, chargebacks, inaccurate billing information, taxes, and any bank or provider fees
          associated with your purchase.
        </p>
      </section>

      <section id="refunds">
        <h2>10. Cancellations, credits, and refunds</h2>
        <p>
          Unless checkout terms say otherwise, paid purchases provide access to the selected plan or
          credits for the period or quantity described at checkout. Unused credits or plan features
          may expire, be subject to daily limits, or be tied to the account that purchased them.
        </p>
        <p>
          Refunds are reviewed case by case. We may issue a full or partial refund, service credit,
          extension, or other remedy when we determine that a duplicate charge, failed payment
          verification, material service access issue, or similar problem occurred. We may decline
          refund requests where usage has already occurred, the issue is outside our control, payment
          abuse is suspected, or applicable law does not require a refund.
        </p>
        <p>
          If subscriptions or renewals are enabled, cancellations stop future renewal charges but do
          not automatically refund prior charges unless required by law or approved by us in writing.
        </p>
      </section>

      <section id="third-parties">
        <h2>11. Third-party services and providers</h2>
        <p>
          InterAI depends on third-party services for authentication, payments, AI inference, speech
          transcription, text-to-speech, analytics, observability, hosting, storage, email, support,
          code execution, resume parsing, and other infrastructure. Examples include OpenAI, Google
          Sign-In, Razorpay, the isolated code sandbox, PostHog, Sentry, Langfuse-compatible telemetry, cloud
          providers, and email providers.
        </p>
        <p>
          When you use InterAI, content you submit — including resume text, profile details,
          interview answers, transcripts, voice audio, code, and support messages — may be transmitted
          to these providers so the service can function. InterAI applies automated redaction before
          some external AI requests, but that process is not perfect and does not cover every provider
          or every data type. Some personal or identifying information may still be sent. See our
          Privacy Policy for a fuller description.
        </p>
        <p>
          Third-party services have their own terms, policies, fees, outages, rate limits, security
          controls, retention practices, and data uses. InterAI is not responsible for third-party
          services except to the extent required by applicable law or by our direct commitments in
          these Terms.
        </p>
      </section>

      <section id="privacy">
        <h2>12. Privacy, cookies, and communications</h2>
        <p>
          Our Privacy Policy explains how we collect, use, store, disclose, protect, export, and
          delete personal information and service data — including when that information is sent to
          external AI and infrastructure providers. By using InterAI, you acknowledge and consent to
          the practices described in the Privacy Policy, including:
        </p>
        <ul>
          <li>transmission of resume, interview, voice, code, and related content to third-party providers;</li>
          <li>best-effort automated redaction that does not guarantee complete removal of personal identifiers;</li>
          <li>the use of cookies or similar technologies for authentication, preferences, security, analytics, and service operation.</li>
        </ul>
        <p>
          We may send transactional, security, account, verification, billing, support, and service
          notices. If you opt into or do not opt out of optional emails, we may also send product
          updates or practice reminders. You can change certain communication preferences in
          settings where available.
        </p>
      </section>

      <section id="availability">
        <h2>13. Availability, changes, suspension, and termination</h2>
        <p>
          We may add, remove, suspend, limit, update, or discontinue features, providers, models,
          plans, credits, integrations, or pages at any time. We may interrupt the service for
          maintenance, security, abuse prevention, provider outages, capacity limits, legal reasons,
          or product changes.
        </p>
        <p>
          We may suspend or terminate your account or access if you violate these Terms, create
          risk, cause harm, attempt fraud or abuse, trigger severe integrity violations, fail to pay,
          misuse technical execution, or if continued service would expose InterAI or others to legal
          or security risk. You may stop using InterAI at any time and may delete your account from
          settings where available.
        </p>
      </section>

      <section id="ip">
        <h2>14. InterAI intellectual property and feedback</h2>
        <p>
          InterAI and its licensors own the service, software, design, user interface, workflows,
          models, prompts where proprietary, scoring systems, reports templates, trademarks, logos,
          documentation, and all related intellectual property, excluding your User Content. We grant
          you a limited, revocable, non-exclusive, non-transferable right to use InterAI for personal
          interview preparation according to these Terms and your plan.
        </p>
        <p>
          If you send ideas, feedback, bug reports, suggestions, or feature requests, you grant us a
          perpetual, worldwide, irrevocable, royalty-free license to use them without restriction or
          compensation, while respecting personal information as described in the Privacy Policy.
        </p>
      </section>

      <section id="disclaimers">
        <h2>15. Disclaimers</h2>
        <p>
          InterAI is provided on an "as is" and "as available" basis. To the maximum extent permitted
          by law, we disclaim all warranties, whether express, implied, statutory, or otherwise,
          including warranties of merchantability, fitness for a particular purpose, title,
          non-infringement, accuracy, availability, security, uninterrupted operation, and error-free
          performance.
        </p>
        <p>
          We do not warrant that interviews, reports, scores, transcriptions, body-language metrics,
          code execution results, technical evaluations, model output, resume parsing, payment flows,
          or integrations will be accurate, complete, available, secure, or suitable for your goals.
        </p>
      </section>

      <section id="liability">
        <h2>16. Limitation of liability and indemnity</h2>
        <p>
          To the maximum extent permitted by law, InterAI will not be liable for indirect,
          incidental, special, consequential, exemplary, or punitive damages, or for lost profits,
          lost revenue, lost opportunities, lost employment outcomes, lost data, business
          interruption, reputational harm, or procurement of substitute services.
        </p>
        <p>
          To the maximum extent permitted by law, InterAI's total liability for all claims relating
          to the service or these Terms will not exceed the greater of the amount you paid to InterAI
          for the service in the three months before the event giving rise to the claim or INR 1,000.
          Some laws do not allow certain limitations, so some limits may not apply to you.
        </p>
        <p>
          You agree to defend, indemnify, and hold harmless InterAI and its affiliates, personnel,
          vendors, and representatives from claims, losses, liabilities, damages, costs, and expenses
          arising from your User Content, your misuse of the service, your violation of these Terms,
          your violation of law, or your violation of third-party rights.
        </p>
      </section>

      <section id="law">
        <h2>17. Governing law and disputes</h2>
        <p>
          These Terms are governed by the laws of India, without regard to conflict-of-law rules.
          Subject to any mandatory consumer rights or applicable law, courts located in India will
          have jurisdiction over disputes arising from or relating to these Terms or InterAI.
        </p>
        <p>
          Before starting a formal claim, you agree to contact us and try to resolve the issue
          informally. This does not limit either party's right to seek urgent injunctive or equitable
          relief where appropriate.
        </p>
      </section>

      <section id="contact">
        <h2>18. Changes and contact</h2>
        <p>
          We may update these Terms from time to time. If changes are material, we may provide notice
          through the service, email, or another reasonable method. Continued use after an update
          means you accept the updated Terms.
        </p>
        <p><PublicContactDetails /></p>
      </section>
    </LegalPageShell>
  )
}
