-- PrepMate local schema version 2: encrypted and lifecycle columns.
-- Generated by scripts/build_local_migrations.py; review and commit changes.

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS resume_payload_encrypted BLOB;

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS facts_encrypted BLOB;

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS derived_taxonomy TEXT NOT NULL DEFAULT '{}';

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS is_active INTEGER NOT NULL DEFAULT 0;

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS confirmation_status TEXT NOT NULL DEFAULT 'needs_review';

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS encryption_status TEXT NOT NULL DEFAULT 'local';

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS updated_at TEXT;

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS parent_resume_id TEXT;

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS superseded_at TEXT;

ALTER TABLE ResumeVersions ADD COLUMN IF NOT EXISTS immutable_at TEXT;

ALTER TABLE UserInfo ADD COLUMN IF NOT EXISTS active_resume_id TEXT;

ALTER TABLE JobProfiles ADD COLUMN IF NOT EXISTS experience_level TEXT;

ALTER TABLE JobProfiles ADD COLUMN IF NOT EXISTS parser_version TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS blueprint_id TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS start_idempotency_key TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS started_at TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS deadline_at TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS report_json_encrypted BLOB;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS transcript_encrypted BLOB;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS analysis_job_id TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS integrity_status TEXT NOT NULL DEFAULT 'clean';

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS lifecycle_revision INTEGER NOT NULL DEFAULT 1;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS recovery_deadline_at TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS completion_kind TEXT;

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS context_snapshot_id TEXT;

ALTER TABLE InterviewQuestions ADD COLUMN IF NOT EXISTS question_spec_id TEXT;

ALTER TABLE InterviewQuestions ADD COLUMN IF NOT EXISTS max_followups INTEGER NOT NULL DEFAULT 2;

ALTER TABLE InterviewQuestions ADD COLUMN IF NOT EXISTS time_budget_seconds INTEGER;

ALTER TABLE InterviewQuestions ADD COLUMN IF NOT EXISTS claim_ids TEXT NOT NULL DEFAULT '[]';

ALTER TABLE InterviewQuestions ADD COLUMN IF NOT EXISTS expected_point_ids TEXT NOT NULL DEFAULT '[]';

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS evidence_hash TEXT;

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS answer_text_encrypted BLOB;

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS transcript_encrypted BLOB;

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS raw_answer_hash TEXT;

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS input_mode TEXT NOT NULL DEFAULT 'text';

ALTER TABLE InterviewResponses ADD COLUMN IF NOT EXISTS timing_json TEXT NOT NULL DEFAULT '{}';

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS round_spec_id TEXT;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS problem_id TEXT;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS round_number INTEGER;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS round_spec TEXT NOT NULL DEFAULT '{}';

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS duration_seconds INTEGER NOT NULL DEFAULT 3600;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS deadline_at TEXT;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS mode TEXT NOT NULL DEFAULT 'mock';

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS max_submissions INTEGER NOT NULL DEFAULT 1;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS problem_version INTEGER;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS workflow_state TEXT NOT NULL DEFAULT '{}';

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS started_at TEXT;

ALTER TABLE TechnicalInterviewRounds ADD COLUMN IF NOT EXISTS whiteboard_encrypted BLOB;

ALTER TABLE TechnicalRunEvents ADD COLUMN IF NOT EXISTS source_code_encrypted BLOB;

ALTER TABLE TechnicalCodeSnapshots ADD COLUMN IF NOT EXISTS source_code_encrypted BLOB;

ALTER TABLE TechnicalSubmissions ADD COLUMN IF NOT EXISTS source_code_encrypted BLOB;

ALTER TABLE TechnicalSubmissions ADD COLUMN IF NOT EXISTS execution_job_id TEXT;

ALTER TABLE TechnicalProblemBank ADD COLUMN IF NOT EXISTS problem_family_id TEXT;

ALTER TABLE TechnicalReasoningEvidence ADD COLUMN IF NOT EXISTS content_encrypted BLOB;

ALTER TABLE TechnicalReasoningEvidence ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

ALTER TABLE TechnicalReasoningEvidence ADD COLUMN IF NOT EXISTS evidence_hash TEXT;

ALTER TABLE TechnicalTelemetryEvents ADD COLUMN IF NOT EXISTS payload_encrypted BLOB;

ALTER TABLE TechnicalTelemetryEvents ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

ALTER TABLE AnalysisStageOutputs ADD COLUMN IF NOT EXISTS output_encrypted BLOB;

ALTER TABLE SessionPerformanceAnalyses ADD COLUMN IF NOT EXISTS analysis_json_encrypted BLOB;

ALTER TABLE SessionPerformanceAnalyses ADD COLUMN IF NOT EXISTS evidence_index_encrypted BLOB;

ALTER TABLE MissionValidationEvidence ADD COLUMN IF NOT EXISTS source_key TEXT;

ALTER TABLE MissionValidationEvidence ADD COLUMN IF NOT EXISTS evidence_hash TEXT;

ALTER TABLE InterviewBlueprints ADD COLUMN IF NOT EXISTS blueprint_json_encrypted BLOB;

ALTER TABLE ImprovementAttemptSessions ADD COLUMN IF NOT EXISTS draft_payload_encrypted BLOB;

ALTER TABLE ExerciseAttempts ADD COLUMN IF NOT EXISTS submitted_answer_encrypted BLOB;

ALTER TABLE ExerciseAttempts ADD COLUMN IF NOT EXISTS submitted_payload_encrypted BLOB;

ALTER TABLE ExerciseAttempts ADD COLUMN IF NOT EXISTS feedback_encrypted BLOB;
