-- PrepMate local schema version 3: indexes and atomic-claim constraints.
-- Generated by scripts/build_local_migrations.py; review and commit changes.

CREATE INDEX IF NOT EXISTS idx_analysis_jobs_claimable
    ON AnalysisJobs (status, next_attempt_at, lease_expires_at, created_at);

CREATE INDEX IF NOT EXISTS idx_analysis_jobs_interview ON AnalysisJobs (interview_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_analysis_stage_outputs_job ON AnalysisStageOutputs (job_id, stage_name);

CREATE INDEX IF NOT EXISTS idx_self_review_events_interview ON SelfReviewEvents (interview_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_client_body_language_interview ON ClientBodyLanguageMetrics (interview_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_coach_exercises_user_status ON CoachExercises (user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_code_snapshots_round ON TechnicalCodeSnapshots (round_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_exercise_attempts_mission ON ExerciseAttempts (mission_id, roadmap_node_id, created_at);

CREATE INDEX IF NOT EXISTS idx_exercise_attempts_user ON ExerciseAttempts (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_generated_exercises_mission ON GeneratedExercises (mission_id, roadmap_node_id);

CREATE INDEX IF NOT EXISTS idx_generated_exercises_user_status ON GeneratedExercises (user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_improve_attempt_sessions_deadline ON ImprovementAttemptSessions (user_id, status, expires_at, deadline_at);

CREATE INDEX IF NOT EXISTS idx_improvement_attempt_sessions_user ON ImprovementAttemptSessions (user_id, status, updated_at);

CREATE INDEX IF NOT EXISTS idx_improvement_events_mission_created ON ImprovementMissionEvents (mission_id, created_at);

CREATE INDEX IF NOT EXISTS idx_improvement_events_user_created ON ImprovementMissionEvents (user_id, created_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_improvement_missions_one_active_per_mode ON ImprovementMissions (user_id, mode) WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_improvement_missions_user_mode_status ON ImprovementMissions (user_id, mode, status, created_at);

CREATE INDEX IF NOT EXISTS idx_improvement_missions_user_status ON ImprovementMissions (user_id, status, created_at);

CREATE INDEX IF NOT EXISTS idx_improvement_nodes_mission_order ON ImprovementRoadmapNodes (mission_id, order_index);

CREATE INDEX IF NOT EXISTS idx_improvement_nodes_user_availability ON ImprovementRoadmapNodes (user_id, availability_status, updated_at);

CREATE INDEX IF NOT EXISTS idx_improvement_skills_mission ON ImprovementMissionSkills (mission_id, skill_key);

CREATE INDEX IF NOT EXISTS idx_improvement_skills_user_status ON ImprovementMissionSkills (user_id, mastery_status, updated_at);

CREATE INDEX IF NOT EXISTS idx_interviews_created ON Interviews (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_interviews_job_profile ON Interviews (job_profile_id);

CREATE INDEX IF NOT EXISTS idx_interviews_resume ON Interviews (resume_id);

CREATE INDEX IF NOT EXISTS idx_interviews_status ON Interviews (status);

CREATE INDEX IF NOT EXISTS idx_interviews_user ON Interviews (user_id);

CREATE INDEX IF NOT EXISTS idx_iq_blueprint_section ON InterviewQuestions (interview_id, blueprint_section_id);

CREATE INDEX IF NOT EXISTS idx_iq_interview ON InterviewQuestions (interview_id);

CREATE INDEX IF NOT EXISTS idx_iq_taxonomy_keys ON InterviewQuestions (taxonomy_keys);

CREATE INDEX IF NOT EXISTS idx_ir_interview ON InterviewResponses (interview_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_interview_response_idempotency
    ON InterviewResponses (interview_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_job_profiles_user ON JobProfiles (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_learner_skill_states_user ON LearnerSkillStates (user_id, mastery_score ASC, next_review_at ASC);

CREATE INDEX IF NOT EXISTS idx_session_review_events_interview ON SessionReviewEvents (interview_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_media_assets_interview ON InterviewMediaAssets (interview_id, media_kind, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_media_coaching_signals_interview ON MediaCoachingSignals (interview_id, severity, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_project_gaps_user_status ON ProjectKnowledgeGaps (user_id, status, next_check_at ASC);

CREATE INDEX IF NOT EXISTS idx_report_artifact_analysis ON ReportArtifacts (analysis_id, status);

CREATE INDEX IF NOT EXISTS idx_report_artifacts_interview ON ReportArtifacts (interview_id, audience);

CREATE INDEX IF NOT EXISTS idx_report_side_effect_outbox_analysis
    ON ReportSideEffectOutbox (analysis_id, event_type);

CREATE INDEX IF NOT EXISTS idx_report_side_effect_outbox_claim
    ON ReportSideEffectOutbox (status, available_at, created_at);

CREATE INDEX IF NOT EXISTS idx_response_assessments_interview ON ResponseAssessments (interview_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_resume_processing_jobs_claim
    ON ResumeProcessingJobs (status, available_at, created_at);

CREATE INDEX IF NOT EXISTS idx_resume_processing_jobs_user
    ON ResumeProcessingJobs (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_resume_versions_user ON ResumeVersions (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_rul_user_time ON ResumeUploadLogs (user_id, uploaded_at DESC);

CREATE INDEX IF NOT EXISTS idx_session_perf_user_mode ON SessionPerformanceAnalyses (user_id, mode, created_at);

CREATE INDEX IF NOT EXISTS idx_skill_evidence_user_skill ON SkillEvidenceEvents (user_id, skill_key, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_technical_attempt_owner_state
    ON TechnicalAttemptAggregates (user_id, lifecycle_state, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_technical_mistakes_user ON TechnicalMistakeClusters (user_id, occurrence_count DESC, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_technical_reasoning_round ON TechnicalReasoningEvidence (round_id, created_at);

CREATE INDEX IF NOT EXISTS idx_technical_reasoning_user ON TechnicalReasoningEvidence (user_id, created_at);

CREATE INDEX IF NOT EXISTS idx_technical_rounds_interview ON TechnicalInterviewRounds (interview_id, round_type);

CREATE INDEX IF NOT EXISTS idx_technical_run_events_round ON TechnicalRunEvents (round_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_technical_submissions_round ON TechnicalSubmissions (round_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_technical_telemetry_interview ON TechnicalTelemetryEvents (interview_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_userinfo_job ON UserInfo (job_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_analysis_job_idempotency ON AnalysisJobs (user_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_analysis_stage_outputs_evidence
    ON AnalysisStageOutputs (job_id, stage_name, stage_version, evidence_hash);

CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_manifest_current ON EvidenceManifests (interview_id) WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_manifest_hash_producer
    ON EvidenceManifests (interview_id, evidence_hash, producer_version);

CREATE UNIQUE INDEX IF NOT EXISTS uq_evidence_manifest_revision ON EvidenceManifests (interview_id, revision_no);

CREATE UNIQUE INDEX IF NOT EXISTS uq_exercise_attempts_idempotency ON ExerciseAttempts (user_id, exercise_id, idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_improvement_nodes_one_current_per_mission ON ImprovementRoadmapNodes (mission_id) WHERE availability_status = 'current';

CREATE UNIQUE INDEX IF NOT EXISTS uq_report_artifact_publication_key ON ReportArtifacts (publication_key);

CREATE UNIQUE INDEX IF NOT EXISTS uq_session_performance_current
    ON SessionPerformanceAnalyses (interview_id, mode, schema_version) WHERE is_current;

CREATE UNIQUE INDEX IF NOT EXISTS uq_session_performance_revision
    ON SessionPerformanceAnalyses (interview_id, mode, schema_version, revision_no);

CREATE UNIQUE INDEX IF NOT EXISTS uq_session_performance_staged_identity
    ON SessionPerformanceAnalyses (
        interview_id, mode, schema_version, evidence_hash, producer_version
    ) WHERE status = 'staged';

CREATE UNIQUE INDEX IF NOT EXISTS uq_skill_evidence_source
    ON SkillEvidenceEvents (user_id, skill_key, source_type, source_id, evaluator_version);
