-- PrepMate local schema version 4: encrypt detailed analysis and outbox payloads.
-- Generated by scripts/build_local_migrations.py; review and commit changes.

ALTER TABLE ResponseAssessments ADD COLUMN IF NOT EXISTS assessment_json_encrypted BLOB;

ALTER TABLE ReportSideEffectOutbox ADD COLUMN IF NOT EXISTS payload_encrypted BLOB;
