-- PrepMate local schema version 5: encrypt resume-derived interview session state.
-- Generated by scripts/build_local_migrations.py; review and commit changes.

ALTER TABLE Interviews ADD COLUMN IF NOT EXISTS questions_data_encrypted BLOB;
